import time
print("Bot 1 Run")
time.sleep(1)
print("Stoped 1s")
print("Bot 1 Run")
time.sleep(1)
print("Stoped 1s")
print("Bot 1 Run")
time.sleep(1)
print("Stoped 1s")
print("Bot 1 Run")
time.sleep(1)
print("Stoped 1s")
print("Bot 1 Run")
time.sleep(1)
print("Stoped 1s")
print("Bot 1 Run")
time.sleep(1)
print("Stoped 1s")
print("Bot 1 Run")
time.sleep(1)
print("Stoped 1s")
print("Bot 1 Run")
time.sleep(1)
print("Stoped 1s")
print("Bot 1 Run")
time.sleep(1)
print("Stoped 1s")
print("Bot 1 Run")
time.sleep(1)
print("Stoped 1s")
print("Bot 1 Run")
time.sleep(1)
print("Stoped 1s")
