import time
print("Bot 2 Run")
time.sleep(1)
print("Stoped 1s")
print("Bot 2 Run")
time.sleep(1)
print("Stoped 1s")
print("Bot 2 Run")
time.sleep(1)
print("Stoped 1s")
print("Bot 2 Run")
time.sleep(1)
print("Stoped 1s")
print("Bot 2 Run")
time.sleep(1)
print("Stoped 1s")
print("Bot 2 Run")
time.sleep(1)
print("Stoped 1s")
print("Bot 2 Run")
time.sleep(1)
print("Stoped 1s")
print("Bot 2 Run")
time.sleep(1)
print("Stoped 1s")
print("Bot 2 Run")
time.sleep(1)
print("Stoped 1s")
print("Bot 2 Run")
time.sleep(1)
print("Stoped 1s")
print("Bot 2 Run")
time.sleep(1)
print("Stoped 1s")
